const $=id=>document.getElementById(id);
const example='MARTÍN GONZÁLEZ\nAnalista de Datos Jr.\n\nPerfil\nEstudiante avanzado de Ingeniería en Sistemas con experiencia en análisis de datos y automatización de reportes.\n\nExperiencia\nDataPlus | Pasante de Business Intelligence | 2025 - Actualidad\n- Elaboré reportes semanales de ventas en Excel y Power BI para el equipo comercial.\n- Limpié bases de datos de clientes y automatizé tareas repetitivas con Python.\n\nEducación\nIngeniería en Sistemas, Universidad Nacional | 2022 - Actualidad\n\nHabilidades\nExcel, Power BI, Python, SQL, comunicación, trabajo en equipo.';
function localAnalysis(cv){const lines=cv.split('\n').filter(Boolean),skills=['Excel','Power BI','Python','SQL','JavaScript','marketing','ventas','comunicación'].filter(s=>new RegExp(s,'i').test(cv));return {perfil:'Perfil profesional con potencial para una presentación más orientada a impacto.',puntaje:Math.min(92,52+skills.length*5),fortalezas:[(skills.length||'Varias')+' habilidad(es) técnica(s) identificada(s).','El CV presenta una estructura de experiencia y formación.','El contenido permite construir un perfil específico sin inventar información.'],oportunidades:['Agregar resultados medibles donde sea posible.','Adaptar el título y las palabras clave a cada puesto objetivo.','Usar verbos de acción al inicio de cada logro.'],palabrasClave:skills.length?skills:['Experiencia','Educación','Habilidades'],cvOptimizado:lines.slice(0,2).join('\n')+'\n\nPERFIL PROFESIONAL\nProfesional con experiencia y habilidades relevantes para el puesto objetivo.\n\nEXPERIENCIA DESTACADA\n'+(lines.filter(x=>/^[•-]/.test(x)).map(x=>'• '+x.replace(/^[•-]\s*/,'')).join('\n')||'• Incorporar aquí los logros y responsabilidades más relevantes.')+'\n\nHABILIDADES\n'+(skills.join(' · ')||'Completar con las herramientas y competencias específicas del CV.')+'\n\nFORMACIÓN\n'+(lines.filter(x=>/universidad|licenciatura|ingenier|educación/i.test(x)).join('\n')||'Mantener la formación consignada en el CV original.'),recomendaciones:['Elegí una oferta laboral concreta y ajustá el resumen profesional.','Revisá que cada logro sea verificable antes de enviarlo.','Guardá una versión en PDF con nombre profesional.']};}
function render(d){$('empty').classList.add('hidden');$('output').classList.remove('hidden');$('profile').textContent=d.perfil;$('score').textContent=d.puntaje;for(const [id,items] of Object.entries({strengths:d.fortalezas,opportunities:d.oportunidades,recommendations:d.recomendaciones})) $(id).innerHTML=items.map(x=>'<li>'+x+'</li>').join('');$('keywords').innerHTML=d.palabrasClave.map(x=>'<span>'+x+'</span>').join('');$('optimizedCV').textContent=d.cvOptimizado;}
const decode=s=>new DOMParser().parseFromString(s,'text/html').documentElement.textContent;
function tags(xml,tag){return [...xml.matchAll(new RegExp('<'+tag+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+tag+'>','g'))].map(m=>decode(m[1])).join(' ');}
async function zipFor(file){if(!window.JSZip)throw Error('No se pudo cargar el lector de archivos. Verificá tu conexión y recargá la página.');return JSZip.loadAsync(await file.arrayBuffer());}
async function officeText(file,ext){const zip=await zipFor(file);if(ext==='docx'){const f=zip.file('word/document.xml');if(!f)throw Error('El Word no tiene contenido legible.');return tags(await f.async('string'),'w:t');}if(ext==='pptx'){const slides=Object.keys(zip.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n)).sort();return (await Promise.all(slides.map(async n=>tags(await zip.file(n).async('string'),'a:t')))).join('\n\n');}const shared=zip.file('xl/sharedStrings.xml')?tags(await zip.file('xl/sharedStrings.xml').async('string'),'t').split(/\s{2,}/):[];const sheets=Object.keys(zip.files).filter(n=>/^xl\/worksheets\/sheet\d+\.xml$/.test(n)).sort();let text='';for(const n of sheets){let xml=await zip.file(n).async('string');xml=xml.replace(/<c[^>]*t="s"[^>]*>\s*<v>(\d+)<\/v>[\s\S]*?<\/c>/g,(_,i)=>shared[i]||'');text+=xml.replace(/<[^>]+>/g,' ')+'\n';}return text.replace(/\s+/g,' ').trim();}
async function readFile(file){const ext=file.name.split('.').pop().toLowerCase();if(!['txt','csv','docx','pptx','xlsx'].includes(ext))throw Error('Formato no compatible. Elegí TXT, CSV, DOCX, PPTX o XLSX.');if(file.size>10*1024*1024)throw Error('El archivo supera el límite de 10 MB.');return ['txt','csv'].includes(ext)?file.text():officeText(file,ext);}
$('loadExample').onclick=()=>{$('cv').value=example;$('fileStatus').textContent='Ejemplo cargado en el campo de texto.';};
$('realAI').onchange=e=>$('apiKey').style.display=e.target.checked?'block':'none';
$('cvFile').onchange=async e=>{const file=e.target.files[0],status=$('fileStatus');if(!file)return;status.className='file-status';status.textContent='Leyendo '+file.name+'...';try{const text=await readFile(file);if(!text.trim())throw Error('No se encontró texto para analizar.');$('cv').value=text;status.textContent='✓ '+file.name+' cargado. Se extrajeron '+text.length.toLocaleString('es-AR')+' caracteres.';}catch(error){status.className='file-status error';status.textContent='No se pudo leer '+file.name+': '+error.message;}};
$('analyze').onclick=async()=>{const cv=$('cv').value.trim(),btn=$('analyze');if(!cv){$('cv').focus();return;}btn.disabled=true;btn.textContent='Analizando...';try{let data;if($('realAI').checked){const r=await fetch('/api/optimize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cv,apiKey:$('apiKey').value})});data=await r.json();if(!r.ok)throw Error(data.error);}else data=localAnalysis(cv);render(data);}catch(e){alert(e.message);}finally{btn.disabled=false;btn.innerHTML='Analizar mi CV <b>→</b>';}};
$('copy').onclick=async()=>{await navigator.clipboard.writeText($('optimizedCV').textContent);$('copy').textContent='¡Copiado!';setTimeout(()=>$('copy').textContent='Copiar',1500);};
